
server:
  port: 8081
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_job_agent
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mramdaspagar@gmail.com
    password: zzyglphtvqtrqrqk

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
app:
  jwt:
    secret: my-secret-key-12345678901234567890
    expiration-ms: 3600000
    refresh-expiration-ms: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
